from __future__ import annotations

import copy
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

import httpx

from .paths import CITY_CONFIG_DIR, DATA_DIR


Fixture = dict[str, Any]


@lru_cache(maxsize=16)
def load_json(path: str) -> Fixture:
    with Path(path).open("r", encoding="utf-8") as file:
        return json.load(file)


OPEN_METEO_FORECAST_URL = "https://api.open-meteo.com/v1/forecast"
WEATHER_SOURCE_ENV = "MOMENTMARKT_WEATHER_SOURCE"


def load_weather(city: str, fixture: str | None = None) -> Fixture:
    """Load weather for a city.

    Local tests and development use committed Open-Meteo snapshots for
    deterministic demo behaviour. The deployed Space can opt into live
    Open-Meteo with ``MOMENTMARKT_WEATHER_SOURCE=live``; failures fall back
    to the same fixture shape so the demo never loses its weather payload.
    """

    fixture_name = fixture or city
    fallback = copy.deepcopy(load_json(str(DATA_DIR / "weather" / f"{fixture_name}.json")))
    if os.environ.get(WEATHER_SOURCE_ENV, "fixture").lower() != "live":
        fallback["momentmarkt_source"] = "open_meteo_fixture"
        return fallback

    try:
        live = _fetch_open_meteo_weather(fallback)
    except Exception as exc:  # pragma: no cover - exercised through tests via monkeypatch
        fallback["momentmarkt_source"] = "open_meteo_fixture_fallback"
        fallback["momentmarkt_source_error"] = exc.__class__.__name__
        return fallback

    live["momentmarkt_source"] = "open_meteo_live"
    return live


def _fetch_open_meteo_weather(fallback: Fixture) -> Fixture:
    latitude = fallback.get("latitude")
    longitude = fallback.get("longitude")
    if latitude is None or longitude is None:
        raise ValueError("weather fixture is missing latitude/longitude")

    response = httpx.get(
        OPEN_METEO_FORECAST_URL,
        params={
            "latitude": latitude,
            "longitude": longitude,
            "current": ",".join(
                [
                    "temperature_2m",
                    "precipitation",
                    "weather_code",
                    "wind_speed_10m",
                    "relative_humidity_2m",
                ]
            ),
            "hourly": ",".join(
                [
                    "temperature_2m",
                    "precipitation_probability",
                    "precipitation",
                    "weather_code",
                ]
            ),
            "timezone": fallback.get("timezone", "auto"),
            "forecast_days": 2,
        },
        timeout=2.0,
    )
    response.raise_for_status()
    return response.json()


def load_events(city: str) -> Fixture:
    return load_json(str(DATA_DIR / "events" / f"{city}-events.json"))


def load_density(city: str) -> Fixture:
    return load_json(str(DATA_DIR / "transactions" / f"{city}-density.json"))


def load_density_synthesized(city: str) -> Fixture | None:
    """Return the synthesized signal-context layer for `city`, if present.

    Generated by `momentmarkt_backend.scripts.synthesize_signal_contexts`.
    Returns ``None`` if the file does not exist (so callers can degrade
    cleanly to canonical-only behaviour).
    """
    path = DATA_DIR / "transactions" / f"{city}-density-synthesized.json"
    if not path.exists():
        return None
    return load_json(str(path))


@lru_cache(maxsize=16)
def load_density_merged(city: str, fixture: str | None = None) -> Fixture:
    """Return density with canonical merchants + synthesized layer merged.

    - ``fixture`` controls which canonical fixture file is loaded (matches
      the existing ``cities/<city>.json::density_fixture`` field). If unset,
      defaults to ``city`` so single-city demos work without a config lookup.
    - The synthesized layer is always keyed by the city slug (Berlin OSM
      catalog → ``berlin-density-synthesized.json``).
    - On id collision the canonical entry wins, byte-identical to what
      ``load_density`` returns. So existing tests that diff canonical
      merchants stay green.
    - If neither layer exists for the city, raises ``FileNotFoundError`` via
      ``load_density``.
    - If only one layer exists, returns just that layer.
    """
    fixture_name = fixture or city
    try:
        canonical = copy.deepcopy(load_density(fixture_name))
    except FileNotFoundError:
        canonical = None

    synth = load_density_synthesized(city)
    if synth is not None:
        synth = copy.deepcopy(synth)

    if canonical is None and synth is None:
        # Re-raise the original FileNotFoundError shape from load_density.
        return load_density(fixture_name)
    if canonical is None:
        return synth  # type: ignore[return-value]
    if synth is None:
        return canonical

    canonical_ids = {m["id"] for m in canonical.get("merchants", [])}
    extra = [m for m in synth.get("merchants", []) if m["id"] not in canonical_ids]
    canonical["merchants"] = list(canonical.get("merchants", [])) + extra
    return canonical


def load_city_config(city: str) -> Fixture:
    return load_json(str(CITY_CONFIG_DIR / f"{city}.json"))


def available_cities() -> list[str]:
    if not CITY_CONFIG_DIR.exists():
        return []
    return sorted(path.stem for path in CITY_CONFIG_DIR.glob("*.json"))
